#!/usr/bin/env python3
"""Compare regenerated manuscript artifacts against the submitted reference.

Reference copies (``artifacts/reference/``) are byte-exact copies of the
table/figure files included in the submitted manuscript. Regenerated copies
land in ``artifacts/tables`` and ``artifacts/figures`` via
``make reproduce-paper``.

Checks (any failure exits non-zero):
  * every generated table is byte-identical to its reference;
  * every generated figure PNG (dpi=300) is byte-identical to its reference;
  * the figure PDFs match after stripping the volatile /CreationDate and
    /ModDate metadata (PDF font-stream packing is not bit-stable across
    matplotlib versions, so the PNG check is the strict pixel check);
  * the regenerated statistics CSVs match the SHA-256 digests recorded in
    the release manifest.

Two manuscript tables are intentionally absent from the generated set:
``table_provenance.tex`` (Table 2) is a descriptive trust-boundary table and
``table_gate_auth.tex`` (Table 6) was typeset by hand from
``code/results/ijcip_final/gate_auth/gate_auth_summary.csv``; both are shipped
as reference files and covered by checksums (see docs/PAPER_ARTIFACT_MAP.md).
"""
from __future__ import annotations

import hashlib
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REF_T = ROOT / "artifacts/reference/tables"
REF_F = ROOT / "artifacts/reference/figures"
GEN_T = ROOT / "artifacts/tables"
GEN_F = ROOT / "artifacts/figures"
MANIFEST = ROOT / "data/manifests/release_manifest.json"

GENERATED_TABLES = [
    "table_gate_v3.tex", "table_eh_v3.tex", "table_holdout_v3.tex",
    "table_adversarial_v3_qwen.tex", "table_adversarial_v3_llama.tex",
    "table_stats_primary.tex", "table_latency_v3.tex",
]
HAND_AUTHORED = ["table_provenance.tex", "table_gate_auth.tex"]
FIGURES = ["fig_containment_v3", "fig_gate_v3", "fig_holdout_ens_diff"]

_DATE = re.compile(rb"/(CreationDate|ModDate) \(D:[^)]*\)")


def _sha(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def main() -> int:
    failures: list[str] = []
    ok = 0

    for name in GENERATED_TABLES:
        gen, ref = GEN_T / name, REF_T / name
        if not gen.exists():
            failures.append(f"missing generated table: {gen}")
        elif gen.read_bytes() != ref.read_bytes():
            failures.append(f"table differs from manuscript reference: {name}")
        else:
            ok += 1
            print(f"[ok] table byte-identical: {name}")

    for name in HAND_AUTHORED:
        if (REF_T / name).exists():
            print(f"[note] {name}: hand-authored manuscript table, shipped as "
                  f"reference only (not regenerated; see docs/PAPER_ARTIFACT_MAP.md)")
        else:
            failures.append(f"missing reference table: {name}")

    for stem in FIGURES:
        g_png, r_png = GEN_F / f"{stem}.png", REF_F / f"{stem}.png"
        g_pdf, r_pdf = GEN_F / f"{stem}.pdf", REF_F / f"{stem}.pdf"
        if not g_png.exists() or not g_pdf.exists():
            failures.append(f"missing generated figure: {stem}")
            continue
        if g_png.read_bytes() != r_png.read_bytes():
            failures.append(f"figure PNG differs from manuscript reference: {stem}.png")
        else:
            ok += 1
            print(f"[ok] figure PNG byte-identical: {stem}.png")
        if _DATE.sub(b"", g_pdf.read_bytes()) == _DATE.sub(b"", r_pdf.read_bytes()):
            print(f"[ok] figure PDF identical modulo timestamps: {stem}.pdf")
        else:
            print(f"[note] {stem}.pdf differs beyond timestamps (PDF stream "
                  f"packing is matplotlib-version-dependent); the byte-exact "
                  f"PNG check above is authoritative for pixel content")

    # statistics regenerated by run_stats_v3 must match the release manifest
    if MANIFEST.exists():
        man = json.loads(MANIFEST.read_text())
        for e in man["artifacts"]:
            rel = e["relative_path"]
            if rel.startswith("code/results/ijcip_final_v3/statistics/"):
                p = ROOT / rel
                if not p.exists():
                    failures.append(f"missing statistics file: {rel}")
                elif _sha(p) != e["sha256"]:
                    failures.append(
                        f"regenerated statistics differ from canonical: {rel} "
                        f"(investigate numpy/scipy version drift; do NOT "
                        f"update the manifest to force agreement)")
                else:
                    ok += 1
                    print(f"[ok] statistics match canonical digest: {Path(rel).name}")
    else:
        failures.append(f"release manifest not found: {MANIFEST}")

    print(f"\n{ok} artifact comparisons passed, {len(failures)} failed")
    for f in failures:
        print(f"[FAIL] {f}", file=sys.stderr)
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
